# Generated by Django 5.2.4 on 2025-07-31 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='last name')),
                ('nip', models.PositiveBigIntegerField(unique=True, verbose_name='NIP')),
                ('nik', models.PositiveBigIntegerField(unique=True, verbose_name='NIK')),
                ('pangkat_golongan', models.CharField(max_length=20, verbose_name='pangkat/golongan')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('status', models.CharField(choices=[('PNS', 'PNS'), ('PPPK', 'P3K'), ('CPNS', 'CPNS')], max_length=10, verbose_name='status')),
                ('place_of_birth', models.CharField(max_length=50, verbose_name='place of birth')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('pria', 'laki-laki'), ('perempuan', 'perempuan')], max_length=10, verbose_name='gender')),
                ('religion', models.CharField(choices=[('islam', 'ISLAM'), ('kristen', 'KRISTEN'), ('hindu', 'HINDU'), ('budha', 'BUDHA'), ('konghuchu', 'KONGHUCHU')], max_length=10, verbose_name='religion')),
                ('institution', models.CharField(max_length=200, verbose_name='institution')),
                ('account', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='account')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'account_profiles',
            },
        ),
    ]
