# Generated by Django 5.2.4 on 2025-07-30 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_accounts_options_alter_accounts_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='last_name',
        ),
    ]
