# Generated by Django 5.2.4 on 2025-07-31 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_accounts_first_name_remove_accounts_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
    ]
