# Generated by Django 5.2.4 on 2025-07-31 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_accounts_options_profilemodels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodels',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
