# Generated by Django 5.2.4 on 2025-07-31 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_profilemodels_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profilemodels',
            table='account_profiles',
        ),
    ]
